# Default values for poke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: omkarhatlage17/pokemon-scanner
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest


service:
  enabled: false

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
